import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    padding: 12,
    paddingTop: 20,
    paddingBottom: 120, // Aggiunto spazio extra per la tabbar
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 16,
  },
  title: { 
    fontSize: 28,
    marginTop: 30,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 10,
    letterSpacing: -0.5,
  },
  subtitle: { 
    fontSize: 16,
    color: 'rgba(255,255,255,0.7)',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  inputSection: {
    alignItems: 'center',
    marginBottom: 20,
    gap: 18,
  },
  inputBlurContainer: {
    borderRadius: 50,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 32,
    paddingVertical: 14,
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    minWidth: 100,
  },
  rollButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 15,
    paddingHorizontal: 32,
    borderRadius: 24,
    shadowColor: '#a855f7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '700',
    color: 'white',
    letterSpacing: 0.5,
  },
  resultsSection: {
    marginBottom: 20,
  },
  resultsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 30,
    marginTop: -8,
    letterSpacing: -0.5,
    marginLeft: 18,
  },
  diceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
    paddingBottom: 16, // Aggiunto padding
  },
  diceCard: {
    width: 70,
    height: 70,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  diceGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  diceEmoji: {
    fontSize: 36,
    color: 'white',
    marginBottom: 2,
  },
  diceValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  totalSection: {
    marginTop: 18,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 16,
    padding: 16,
    marginEnd:80,
    marginStart:80,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  totalText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.5,
  },
  footerText: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.4)',
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 15, // Aggiunto margin bottom
    letterSpacing: 0.5,
  },
});